name: Rust

on:
  push:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always
  PKG_CONFIG_ALLOW_CROSS: 1

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Install Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    
    - name: Cross compile for Windows
      run: cargo build --release --target x86_64-pc-windows-gnu
      env:
        PKG_CONFIG_ALLOW_CROSS: 1
      
    - name: Cross compile for macOS ARM
      run: cargo build --release --target aarch64-apple-darwin
      env:
        PKG_CONFIG_ALLOW_CROSS: 1
    
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.3.1
      with:
        name: sbsrf-update-macos-aarch64
        path: |
          target/x86_64-pc-windows-gnu/release/sbsrf-update.exe
          target/aarch64-apple-darwin/release/sbsrf-update
